#!/usr/bin/env python3
"""Generate the 12 bsaha200m HP-sweep configs from one in-file template.

One base + patched deltas (not 12 hand-maintained files). Re-run to regenerate.

  10 x s8e4_bmoe : 8 softmax+stdMoE layers, then 4 energy_attention+EnergyFF_BoltzmannMoE
   2 x s12_stdmoe: 12 softmax+stdMoE layers (the baseline)

Every arm: 200M total, K=32 top-2 energy experts, 4 GPUs x mb4 x ga8 x seq4096
= 524,288 tok/step x 30000 = 15.73B tokens.
"""
import os

H, LAYERS, VOCAB = 768, 12, 100352
STD_IPE_S8E4 = 384     # PER-EXPERT width (MoE intermediate_size is per-expert)
STD_IPE_S12  = 427     # PER-EXPERT width
ENERGY_IPE   = 12256   # 32 experts x 383 (solved against the real builder)
STEPS, MB, GA, GPUS, SEQ = 30000, 4, 8, 4, 4096

DATA = "/proj/datasets/ndehmamy-dataset-rescue"
TOK = f"{DATA}/tokenizers/granite-4.0-tiktoken"
SAVE_ROOT = "/proj/dmfexp/energy-gpt/checkpoints-bsaha/bsaha200m"

HEADER = """# {name} -- 200M HP sweep, {arch}
# AUTO-GENERATED by configs/bsaha200m/_make_configs.py -- edit that, not this file.
#
# {desc}
#
# Geometry: {gpus} GPUs x mb={mb} x ga={ga} x seq={seq} = {tokstep:,} tok/step
#           x {steps} steps = {tokens:.2f}B tokens
# Params:   total {total:,}  active {active:,} ({actpct:.1f}%)
"""

SOFTMAX = ("      - {{sequence_mixer_type: softmax_attention, num_attention_heads: 12, "
           "num_key_value_heads: 12, add_bias: false, attention_multiplier: 0.125}}")
ENERGY_ATTN = ("      - {{sequence_mixer_type: energy_attention, num_attention_heads: 12, "
               "num_key_value_heads: 12, add_bias: false, attention_multiplier: 0.125}}")
STD_MLP = ("      - {{mlp_type: MoE, activation_function: swiglu, intermediate_size: {ipe}, "
           "add_bias: false, num_experts: 8, num_experts_per_tok: 2, normalized_topk: true, "
           "shared_expert_gating: false, use_interleaved_weights: false}}")


def energy_mlp(p, anchor):
    """The EnergyFF_BoltzmannMoE block. `p` carries the swept overrides."""
    lead = "      - &emoe" if anchor else "      - *emoe"
    if not anchor:
        return lead
    return "\n".join([
        lead,
        "        mlp_type: EnergyFF_BoltzmannMoE",
        "        expert_kind: hopfield",
        f"        intermediate_size: {ENERGY_IPE}        # K=32 x I_e=383",
        "        n_experts: 32",
        "        top_k: 2",
        '        e_sign_override: "pos"',
        "        hopfield_grad_scale: sqrt_consistent",
        "        routing_norm: zscore",
        "        temperature: 1.0",
        f"        sinkhorn_iters: {p['sinkhorn_iters']}",
        "        sinkhorn_persist_mu: true",
        "        sinkhorn_mu_iters: 1",
        "        repulsion_tensor_idx: true",
        "        repulsion_form: abs",
        "        repulsion_space: output",
        "        repulsion_coef: 0.1",
        "        repulsion_subsample: 64",
        "        n_repulsion_pairs: 4",
        "        cos_probe_interval: 100",
        "        renormalize_topk: true",
        "        fused_experts: true",
        "        sparse_forward: true",
        "        sparse_start_step: 500",
        f"        sparse_candidates: {p['sparse_candidates']}",
        "        sparse_explore: 2",
        f"        proxy_rank: {p['proxy_rank']}",
        "        proxy_kind: subspace",
        f"        proxy_init: {p['proxy_init']}",
        f"        proxy_out_dim: {p['proxy_out_dim']}",
        "        proxy_iters: 1",
        f"        proxy_loss_coef: {p['proxy_loss_coef']}",
        "        gelu_grad_method: sigmoid",
        "        activation_function: gelu",
    ])


# MEASURED by instantiating each arch on a meta device (not derived from a formula --
# an earlier closed form was wrong twice: MoE `intermediate_size` is PER-EXPERT, and the
# engine's active count discounts only blocks that define get_num_active_parameters()).
# Verify with: configs/bsaha200m/_verify_params.py
MEASURED = {
    "s12":  (199_920_384, 129_086_208),
    "s8e4": (199_983_108, 122_218_500),
}


def count_params(arch):
    return MEASURED[arch]


def build(name, arch, lr, p, desc):
    total, active = count_params(arch)
    tokstep = GPUS * MB * GA * SEQ
    blocks = []
    if arch == "s12":
        for _ in range(LAYERS):
            blocks.append(SOFTMAX.format())
            blocks.append(STD_MLP.format(ipe=STD_IPE_S12))
    else:
        for _ in range(8):
            blocks.append(SOFTMAX.format())
            blocks.append(STD_MLP.format(ipe=STD_IPE_S8E4))
        for i in range(4):
            blocks.append(ENERGY_ATTN.format())
            blocks.append(energy_mlp(p, anchor=(i == 0)))

    head = HEADER.format(name=name, arch=("12 softmax + std MoE (baseline)" if arch == "s12"
                                          else "8 softmax+stdMoE + 4 energy+BoltzmannMoE"),
                         desc=desc, gpus=GPUS, mb=MB, ga=GA, seq=SEQ, tokstep=tokstep,
                         steps=STEPS, tokens=tokstep * STEPS / 1e9,
                         total=total, active=active, actpct=100 * active / total)
    body = f"""
datasets:
  - class_name: MegatronDataset
    data_name: Megatron
    data_sampling_ratio: 1
    class_args:
      eval_steps: 2
      data_cache_path: /proj/dmfexp/energy-gpt/cache-bsaha200m
      data_path:
        - 0.35
        - {DATA}/web-nemotron-cc-hq-p2_0
        - 0.35
        - {DATA}/web-nemotron-cc-hq-p2_1
        - 0.15
        - {DATA}/megamath-web-pro_0
        - 0.15
        - {DATA}/finemath-3plus-rewritten_0
      split: 99,0.5,0.5
      sequence_length: {SEQ}

tokenizer_args:
  tokenizer_name: {TOK}

model_args:
  model_class: AutoModelForCausalLM
  pretrained_config:
    model_type: energy
    initializer_range: 0.02
    layer_norm_epsilon: 1.0e-05
    hidden_size: {H}
    num_layers: {LAYERS}
    layer_iterations: [{', '.join(['1'] * LAYERS)}]
    tie_word_embeddings: true
    vocab_size: {VOCAB}
    bos_token_id: 0
    eos_token_id: 0
    pad_token_id: 0
    max_position_embeddings: {SEQ}
    position_embedding_type: rope
    rope_dim: 64          # REQUIRED: mixed softmax/energy mixers -> rope_dim cannot be inferred
    rope_theta: 10000
    normalization_function: rmsnorm
    m_emb: null
    m_residual: null
    m_width: null
    router_aux_loss_coef: 0.001
    sequence_mixer_blocks:
{chr(10).join(blocks[0::2])}
    mlp_blocks:
{chr(10).join(blocks[1::2])}

tuning_args:
  tuning_method: pretraining

save_args:
  save_path: {SAVE_ROOT}/{name}
  save_interval: 500

load_args:
  load_path: {SAVE_ROOT}/{name}
  iteration: null

logging_args:
  log_interval: 10
  experiments_tracker_name: wandb
  wandb_args:
    project: dolomite
    name: {name}

training_parameters:
  num_training_steps: {STEPS}
  eval_interval: 1000000
  micro_batch_size: {MB}
  gradient_accumulation_steps: {GA}
  eval_during_training: false

optimizer_args:
  class_name: TorchAdamW
  class_args:
    lr: {lr}
    weight_decay: 0.1
    betas: [0.9, 0.95]
    eps: 1.0e-08

lr_scheduler_args:
  lr_decay_style: cosine
  num_warmup_steps: 500
  num_decay_steps: {STEPS - 500}
  lr_decay_factor: 0.1

mixed_precision_args:
  dtype: bf16

distributed_args:
  fsdp_algorithm: 2
  stage: 3
  torch_compile: true
"""
    return head + body


BASE = dict(proxy_rank=16, proxy_out_dim=512, proxy_loss_coef=0.01,
            sparse_candidates=2, sinkhorn_iters=3, proxy_init="random")

ARMS = [
    # --- s8e4_bmoe: 5 LRs at base HPs ---
    ("bs200m_s8e4_bmoe_lr1e-3", "s8e4", "1.0e-3", {}, "LR arm: 1e-3 (half the 400M default)."),
    ("bs200m_s8e4_bmoe_lr2e-3", "s8e4", "2.0e-3", {}, "LR arm: 2e-3. THE ANCHOR -- base HPs, matches the 400M recipe."),
    ("bs200m_s8e4_bmoe_lr3e-3", "s8e4", "3.0e-3", {}, "LR arm: 3e-3."),
    ("bs200m_s8e4_bmoe_lr4e-3", "s8e4", "4.0e-3", {}, "LR arm: 4e-3."),
    ("bs200m_s8e4_bmoe_lr5e-3", "s8e4", "5.0e-3", {}, "LR arm: 5e-3 (upper bracket; watch for divergence)."),
    # --- s8e4_bmoe: 5 proxy/routing arms at lr 2e-3 ---
    ("bs200m_s8e4_bmoe_prank32", "s8e4", "2.0e-3", dict(proxy_rank=32),
     "proxy_rank 16->32. Doubles router capacity; targets proxy_topk_agree (.63-.68 at 400M)."),
    ("bs200m_s8e4_bmoe_pout1024", "s8e4", "2.0e-3", dict(proxy_out_dim=1024),
     "proxy_out_dim 512->1024. Halves the subsample error (~1/sqrt(m)) on the energy estimate."),
    ("bs200m_s8e4_bmoe_pcoef05", "s8e4", "2.0e-3", dict(proxy_loss_coef=0.05),
     "proxy_loss_coef 0.01->0.05. Distils the proxy 5x harder against the exact routing."),
    ("bs200m_s8e4_bmoe_cand4", "s8e4", "2.0e-3", dict(sparse_candidates=4),
     "sparse_candidates 2->4. Wider shortlist: more exact energies, better denominator, less speedup."),
    ("bs200m_s8e4_bmoe_psvd", "s8e4", "2.0e-3", dict(proxy_init="svd"),
     "proxy_init random->svd. Code documents 0.554 vs 0.038 top-2 agreement (6.2x); the 400M run used random."),
    # --- s12 baseline: 2 LRs ---
    ("bs200m_s12_stdmoe_lr2e-3", "s12", "2.0e-3", {}, "Baseline control at the anchor LR."),
    ("bs200m_s12_stdmoe_lr1e-3", "s12", "1.0e-3", {}, "Baseline control at the lower LR."),
]

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    rows = []
    for name, arch, lr, delta, desc in ARMS:
        p = dict(BASE); p.update(delta)
        open(os.path.join(here, name + ".yml"), "w").write(build(name, arch, lr, p, desc))
        tot, act = count_params(arch)
        rows.append((name, arch, lr, tot, act, delta))
    w = max(len(r[0]) for r in rows)
    print(f"{'config'.ljust(w)}  {'arch':5s} {'lr':7s} {'total':>12s} {'active':>12s}  delta")
    for n, a, lr, t, ac, d in rows:
        ds = ", ".join(f"{k}={v}" for k, v in d.items()) or "(base HPs)"
        print(f"{n.ljust(w)}  {a:5s} {lr:7s} {t:>12,} {ac:>12,}  {ds}")
    print(f"\n{len(rows)} configs written to {here}")
